// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SerempreClientAPI.Infrastructure.DataSource;

#nullable disable

namespace SerempreClientAPI.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SerempreClientAPI.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 7, 19, 11, 2, 27, 97, DateTimeKind.Local).AddTicks(5676));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 7, 19, 11, 2, 27, 97, DateTimeKind.Local).AddTicks(6159));

                    b.HasKey("Id");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bogotá"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medellín"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cali"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Barranquilla"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cartagena"
                        });
                });

            modelBuilder.Entity("SerempreClientAPI.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 7, 19, 11, 2, 27, 97, DateTimeKind.Local).AddTicks(6592));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 7, 19, 11, 2, 27, 97, DateTimeKind.Local).AddTicks(7038));

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Antonio Garcia"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Name = "Sonia Flores"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Name = "Ana Gomez"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Name = "Jose Gonzalez"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            Name = "Servelina Montaño"
                        });
                });

            modelBuilder.Entity("SerempreClientAPI.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 7, 19, 11, 2, 27, 97, DateTimeKind.Local).AddTicks(7480));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 7, 19, 11, 2, 27, 97, DateTimeKind.Local).AddTicks(7851));

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@admin.com",
                            Name = "Administrador",
                            Password = "admin123",
                            Photo = "photo1.jpg"
                        });
                });

            modelBuilder.Entity("SerempreClientAPI.Domain.Entities.Client", b =>
                {
                    b.HasOne("SerempreClientAPI.Domain.Entities.City", "City")
                        .WithMany("Clients")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("SerempreClientAPI.Domain.Entities.City", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
